--drop table frames
CREATE TABLE frames (
	id serial4 NOT NULL,
	en varchar,
	pt varchar,
	next_test timestamp,
	num_right_answer integer,
	CONSTRAINT frames_en_pt_key UNIQUE (en, pt),
	CONSTRAINT frames_pkey PRIMARY KEY (id)
);


INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to work', 'Eu quero trabalhar', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to work in the morning', 'Eu quero trabalhar de manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see a glass', 'Eu vejo um copo', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see a boy', 'Eu vejo um menino', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see my sister', 'Eu vejo minha irmã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see a cup of coffee', 'Eu vejo uma xícara de café', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want a cup of coffee', 'Eu quero uma xícara de café', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need a cup of coffee', 'Eu preciso de uma xícara de café', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i drink a cup of coffee', 'Eu bebo uma xícara de café', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to eat', 'Eu quero comer', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to speak', 'Eu quero falar', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to drink', 'Eu quero beber', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to work', 'Eu quero trabalhar', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to eat bread', 'Eu quero comer pão', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to eat cheese', 'Eu quero comer queijo', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to eat ham', 'Eu quero comer presunto', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to eat fish', 'Eu quero comer peixe', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you need to eat fish', 'Você precisa comer peixe', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you need to drink milk', 'Você precisa beber leite', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you need to speak English', 'Você precisa falar inglês', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you need to work tomorrow', 'Você precisa trabalhar amanhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work with you', 'Eu trabalho com você', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work tomorrow', 'Eu trabalho amanhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work in the morning', 'Eu trabalho de manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work and play', 'Eu trabalho e brinco', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i don''t want to work now', 'Eu não quero trabalhar agora', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i don''t want to drink beer', 'Eu não quero beber cerveja', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i don''t want to see your sister', 'Eu não quero ver sua irmã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i don''t want to eat bread', 'Eu não quero comer pão', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work with my brother', 'Eu trabalho com meu irmão', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i play with my daughter', 'Eu brinco com minha filha', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i speak with my children', 'Eu falo com meus filhos', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i drink with my brother', 'Eu bebo com meu irmão', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see a boy and a girl', 'Eu vejo um menino e uma menina', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see a mother and a father', 'Eu vejo uma mãe e um pai', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see cheese and ham with bread', 'Eu vejo queijo e presunto com pão', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see wine and beer', 'Eu vejo vinho e cerveja', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you eat with your father', 'Você come com seu pai', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you drink with your mother', 'Você bebe com sua mãe', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you speak with your children', 'Você fala com seus filhos', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you work with your brother', 'Você trabalha com seu irmão', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need to play with my daughter', 'Eu preciso brincar com minha filha', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need to work with my daughter', 'Eu preciso trabalhar com minha filha', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need to speak with my daughter', 'Eu preciso falar com minha filha', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need to see my daughter', 'Eu preciso ver minha filha', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i eat in the morning', 'Eu como de manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i don''t play in the morning', 'Eu não brinco de manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to work in the morning', 'Eu quero trabalhar de manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i speak German in the morning', 'Eu falo alemão de manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you want to work in the afternoon', 'Você quer trabalhar à tarde', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you want to play in the afternoon', 'Você quer brincar à tarde', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you want to drink beer in the afternoon', 'Você quer beber cerveja à tarde', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you want to speak in the afternoon', 'Você quer falar à tarde', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i eat and drink in the evening', 'Eu como e bebo à noite', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work and play in the evening', 'Eu trabalho e brinco à noite', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see my family in the evening', 'Eu vejo minha família à noite', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need milk in the evening', 'Eu preciso de leite à noite', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need to work today', 'Eu preciso trabalhar hoje', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to play tomorrow', 'Eu quero brincar amanhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to eat now', 'Eu quero comer agora', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('with me', 'comigo', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('sorry', 'desculpa', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('more or less', 'mais ou menos', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want?', 'Você quer?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you study?', 'Você estuda?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do I like fish?', 'Eu gosto de peixe?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Does he work?', 'Ele trabalha?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Does she need my car?', 'Ela precisa do meu carro?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like my teacher.', 'Eu gosto do meu professor.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like my friend.', 'Eu gosto do meu amigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like my family.', 'Eu gosto da minha família.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like my manager.', 'Eu gosto do meu gerente.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I sleep in the evening.', 'Eu durmo à noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I sleep by myself.', 'Eu durmo sozinho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I need to sleep.', 'Eu preciso dormir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to sleep now.', 'Eu quero dormir agora.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you study English?', 'Você estuda inglês?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you study Portuguese?', 'Você estuda português?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like to study?', 'Você gosta de estudar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you study or work?', 'Você estuda ou trabalha?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t study nor work.', 'Eu não estudo nem trabalho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want or need?', 'Você quer ou precisa?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t want nor need.', 'Eu não quero nem preciso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you eat or drink?', 'Você come ou bebe?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t eat nor drink.', 'Eu não como nem bebo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you play or study?', 'Você joga ou estuda?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t play nor study.', 'Eu não jogo nem estudo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like her family.', 'Eu gosto da família dela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like her store.', 'Eu gosto da loja dela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like her manager.', 'Eu gosto do gerente dela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like her coffee.', 'Eu gosto do café dela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to see his sister.', 'Eu quero ver a irmã dele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to work at his store.', 'Eu quero trabalhar na loja dele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to speak with his son.', 'Eu quero falar com o filho dele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to drink with his glass.', 'Eu quero beber no copo dele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I study at the school.', 'Eu estudo na escola.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I work at the store.', 'Eu trabalho na loja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I drink at the bar.', 'Eu bebo no bar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I eat at the restaurant.', 'Eu como no restaurante.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want to go to the church?', 'Você quer ir à igreja?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you need to go to the store?', 'Você precisa ir à loja?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like to go to the movies?', 'Você gosta de ir ao cinema?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you need to go to the school?', 'Você precisa ir à escola?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to go to the movies.', 'Eu quero ir ao cinema.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to go to the school.', 'Eu quero ir à escola.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like to go to the church.', 'Eu gosto de ir à igreja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I need to go to the store.', 'Eu preciso ir à loja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want the juice?', 'Você quer o suco?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want the cup?', 'Você quer a xícara?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want the bread?', 'Você quer o pão?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want the cheese?', 'Você quer o queijo?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like to work?', 'Você gosta de trabalhar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like to sleep?', 'Você gosta de dormir?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like to play?', 'Você gosta de brincar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I only work in the morning.', 'Eu só trabalho de manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I only study with my sister.', 'Eu só estudo com minha irmã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I only like to eat.', 'Eu só gosto de comer.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I only work today.', 'Eu só trabalho hoje.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He needs a manager.', 'Ele precisa de um gerente.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He needs a friend.', 'Ele precisa de um amigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He needs a teacher.', 'Ele precisa de um professor.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He needs a father.', 'Ele precisa de um pai.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She wants a son and a daughter.', 'Ela quer um filho e uma filha.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She wants a glass and a cup.', 'Ela quer um copo e uma xícara.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She wants fish and meat.', 'Ela quer peixe e carne.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She wants only tea.', 'Ela quer apenas chá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('It likes to eat.', 'Gosta de comer.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('It likes to sleep.', 'Gosta de dormir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('It likes to play.', 'Gosta de brincar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('It likes to go with me.', 'Gosta de ir comigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like to drink wine with my friends. Do you like to drink wine?', 'Eu gosto de beber vinho com meus amigos. Você gosta de beber vinho?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Sorry, but I like to drink beer. Only my father wants wine.', 'Desculpe, mas eu gosto de beber cerveja. Apenas meu pai quer vinho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I need to work tomorrow, and I want to sleep now. Good night!', 'Eu preciso trabalhar amanhã e quero dormir agora. Boa noite!', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want to go to the store in the evening? I work at the store!', 'Você quer ir à loja à noite? Eu trabalho na loja!', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I need to speak with my father today. Do you want to go with me?', 'Preciso falar com meu pai hoje. Você quer ir comigo?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t want to go to the store by myself. I want to go with you.', 'Eu não quero ir à loja sozinho. Eu quero ir com você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want to go to the church with my children tomorrow?', 'Você quer ir à igreja com meus filhos amanhã?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t need to speak German. I only speak English.', 'Eu não preciso falar alemão. Eu só falo inglês.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like to eat bread and cheese. Do you like to drink tea?', 'Eu gosto de comer pão e queijo. Você gosta de beber chá?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to drink a glass of water. Thanks, I need to go.', 'Eu quero beber um copo de água. Obrigado, eu preciso ir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to speak only English with my teacher and my family.', 'Eu quero falar apenas inglês com meu professor e minha família.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t need.', 'Eu não preciso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don''t want tea.', 'Eu não quero chá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He doesn''t work.', 'Ele não trabalha.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You don''t like.', 'Você não gosta.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You don''t need to work today.', 'Você não precisa trabalhar hoje.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('It doesn''t like you.', 'Ele não gosta de você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you work?', 'Você trabalha?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like fish?', 'Você gosta de peixe?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Does he drink beer?', 'Ele bebe cerveja?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do I need to go?', 'Eu preciso ir?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you go to school?', 'Você vai à escola?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Does she study?', 'Ela estuda?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I go to Rio.', 'Eu vou ao Rio.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I go to church.', 'Eu vou à igreja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You need to go to my store.', 'Você precisa ir à minha loja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to work for you.', 'Eu quero trabalhar para você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like to work for you.', 'Eu gosto de trabalhar para você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want a book for my son.', 'Eu quero um livro para o meu filho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I study at my school.', 'Eu estudo na minha escola.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I work at his store.', 'Eu trabalho na loja dele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I need to speak to the boy.', 'Eu preciso falar com o menino.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you drink at the bar?', 'Você bebe no bar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('how much', 'quanto', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('how many', 'quantos/quantas', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('everyday', 'todos os dias', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('every week', 'toda semana', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('on the weekend', 'no fim de semana', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('buck', 'dólar', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('to have breakfast', 'tomar café da manhã', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('to have lunch', 'almoçar', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('to have dinner', 'jantar', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you''re welcome', 'de nada', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('see you later', 'até logo', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('where are you from?', 'De onde você é?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('big car', 'carro grande', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('old house', 'casa velha', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('small girl', 'menina pequena', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('good boy', 'menino bom', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We need to work.', 'Nós precisamos trabalhar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We want to sleep.', 'Nós queremos dormir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We have a car.', 'Nós temos um carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We sell fish.', 'Nós vendemos peixe.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all see the store.', 'Vocês veem a loja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all work today.', 'Vocês trabalham hoje.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all have a friend.', 'Vocês têm um amigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all speak English.', 'Vocês falam inglês.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They want some ham.', 'Eles querem presunto.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They need some bread.', 'Eles precisam de pão.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They speak some German.', 'Eles falam um pouco de alemão.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We want our lunch.', 'Nós queremos nosso almoço.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We like our teacher.', 'Nós gostamos do nosso professor.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We see our mother.', 'Nós vemos nossa mãe.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We want out money.', 'Nós queremos nosso dinheiro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all need your books.', 'Vocês precisam dos seus livros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all need your cups.', 'Vocês precisam das suas xícaras.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all need your friends.', 'Vocês precisam dos seus amigos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You all need your home.', 'Vocês precisam da sua casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They like their house.', 'Eles gostam da casa deles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They like their mother.', 'Eles gostam da mãe deles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They like their sister.', 'Eles gostam da irmã deles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They like their church.', 'Eles gostam da igreja deles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I buy fish.', 'Eu compro peixe.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I buy my books.', 'Eu compro meus livros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I buy lunch.', 'Eu compro almoço.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I buy cars.', 'Eu compro carros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Wee want to sell our house.', 'Nós queremos vender nossa casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We need to sell our car.', 'Nós precisamos vender nosso carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We don''t sell animals.', 'Nós não vendemos animais.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We like to sell to you.', 'Nós gostamos de vender para você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you understand English?', 'Você entende inglês?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I only understand Spanish.', 'Eu só entendo espanhol.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Does he understand you?', 'Ele te entende?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We don''t understand.', 'Nós não entendemos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a sister.', 'Eu tenho uma irmã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a car.', 'Eu tenho um carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a wife.', 'Eu tenho uma esposa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a new son.', 'Eu tenho um filho novo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got a sister.', 'Eu tenho uma irmã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got a car.', 'Eu tenho um carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got a wife.', 'Eu tenho uma esposa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got a new son.', 'Eu tenho um filho novo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have to work.', 'Eu tenho que trabalhar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got to work.', 'Eu tenho que trabalhar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have to go.', 'Eu tenho que ir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got to go.', 'Eu tenho que ir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have to sleep.', 'Eu tenho que dormir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I got to sleep.', 'Eu tenho que dormir.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a new home.', 'Eu tenho uma casa nova.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a new car.', 'Eu tenho um carro novo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a new friend.', 'Eu tenho um amigo novo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a new wife.', 'Eu tenho uma esposa nova.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes old cars.', 'Ele gosta de carros antigos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes old friends.', 'Ele gosta de amigos antigos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes old books.', 'Ele gosta de livros antigos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes homes.', 'Ele gosta de casas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like big stores?', 'Você gosta de lojas grandes?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like big cups?', 'Você gosta de xícaras grandes?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like big houses?', 'Você gosta de casas grandes?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you like big girls?', 'Você gosta de meninas grandes?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want a small tree.', 'Eu quero uma árvore pequena.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want a small wife.', 'Eu quero uma esposa pequena.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want a small house.', 'Eu quero uma casa pequena.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want a small glass.', 'Eu quero um copo pequeno.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want some small trees.', 'Eu quero algumas árvores pequenas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want some small glasses.', 'Eu quero alguns copos pequenos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want some big cars.', 'Eu quero alguns carros grandes.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want some big books.', 'Eu quero alguns livros grandes.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What do you buy?', 'O que você compra?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What do you want?', 'O que você quer?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What do you need?', 'O que você precisa?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What do you see?', 'O que você vê?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do they work?', 'Onde eles trabalham?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do they sleep?', 'Onde eles dormem?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do they play?', 'Onde eles brincam?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do they study?', 'Onde eles estudam?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you have to work?', 'Quando você tem que trabalhar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When does she have to study?', 'Quando ela tem que estudar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do they have to sleep?', 'Quando eles têm que dormir?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do I have to go?', 'Quando eu tenho que ir?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you have to sell this car?', 'Quando você tem que vender este carro?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you have to sell this house?', 'Quando você tem que vender esta casa?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you have to sell this bread?', 'Quando você tem que vender este pão?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you have to sell this cheese?', 'Quando você tem que vender este queijo?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to buy that book.', 'Eu quero comprar aquele livro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to buy that glass.', 'Eu quero comprar aquele copo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to buy that house.', 'Eu quero comprar aquela casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to buy that car.', 'Eu quero comprar aquele carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do we have lunch?', 'Quando almoçamos?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do we have lunch with Bob?', 'Quando almoçamos com o Bob?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you want to have lunch?', 'Quando você quer almoçar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you have lunch by yourself?', 'Você almoça sozinho(a)?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do you want to have dinner?', 'Onde você quer jantar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where does he want to have dinner?', 'Onde ele quer jantar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do they want to have dinner?', 'Onde eles querem jantar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do we want to have dinner?', 'Onde nós queremos jantar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like to have breakfast.', 'Eu gosto de tomar café da manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I need to have breakfast.', 'Eu preciso tomar café da manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('To sin is bad.', 'Pecar é ruim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Too thin is bad.', 'Muito magro é ruim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You don’t want to sink.', 'Você não quer afundar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You don’t want to think.', 'Você não quer pensar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We want a song.', 'Nós queremos uma música.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We want a thong.', 'Nós queremos uma tanga.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What sum do you have?', 'Qual soma você tem?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What thumb do you have?', 'Que polegar você tem?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see the pass?', 'Você vê o passe?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see the path?', 'Você vê o caminho?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to go to the store.', 'Eu quero ir à loja.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have to speak to the manager.', 'Eu tenho que falar com o gerente.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I work at the big store.', 'Eu trabalho na loja grande.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I sleep at my house.', 'Eu durmo na minha casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('What does he want?', 'O que ele quer?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do you work?', 'Onde você trabalha?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where are you from?', 'De onde você é?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do you go on the weekend?', 'Para onde você vai no fim de semana?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you have lunch?', 'Quando você almoça?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do they sleep?', 'Quando eles dormem?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you got to go?', 'Quando você tem que ir?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want this book.', 'Eu quero este livro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes this car.', 'Ele gosta deste carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you need this money?', 'Você precisa deste dinheiro?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have that bike.', 'Eu tenho aquela bicicleta.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He needs that ham.', 'Ele precisa daquele presunto.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They go to that church.', 'Eles vão àquela igreja.', now(), 1);

INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You like me.', 'Você gosta de mim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes me.', 'Ele gosta de mim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She likes me.', 'Ela gosta de mim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They like me.', 'Eles gostam de mim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We need you.', 'Nós precisamos de você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Your father needs you.', 'Seu pai precisa de você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She needs you.', 'Ela precisa de você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('It needs you.', 'Isso precisa de você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I understand him.', 'Eu o entendo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They understand him.', 'Eles o entendem.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We understand him.', 'Nós o entendemos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She understands him.', 'Ela o entende.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I work with her.', 'Eu trabalho com ela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He works with her.', 'Ele trabalha com ela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We work with her.', 'Nós trabalhamos com ela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You work with her.', 'Você trabalha com ela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like it.', 'Eu gosto disso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He likes it.', 'Ele gosta disso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She likes it.', 'Ela gosta disso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They like it.', 'Eles gostam disso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They see us play.', 'Eles nos veem jogar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He sees us play.', 'Ele nos vê jogar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You see us play.', 'Você nos vê jogar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She sees us play.', 'Ela nos vê jogar.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I speak with them.', 'Eu falo com eles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We speak with them.', 'Nós falamos com eles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('She speaks with them.', 'Ela fala com eles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They speak with them.', 'Eles falam com eles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They write letters to me.', 'Eles escrevem cartas para mim.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You write numbers for us.', 'Você escreve números para nós.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He writes for a newspaper.', 'Ele escreve para um jornal.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We don’t write to him.', 'Nós não escrevemos para ele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I read the newspaper.', 'Eu leio o jornal.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You read the book.', 'Você lê o livro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We want to read.', 'Nós queremos ler.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He read magazines.', 'Ele lê revistas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We need to help the boy.', 'Nós precisamos ajudar o menino.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You have to help us today.', 'Você tem que nos ajudar hoje.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to help at home.', 'Eu quero ajudar em casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you help your mother?', 'Você ajuda sua mãe?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don’t know your name.', 'Eu não sei o seu nome.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you know her husband?', 'Você conhece o marido dela?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('The waitress doesn’t know English.', 'A garçonete não sabe inglês.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('The boss knows my brother.', 'O chefe conhece meu irmão.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to give you bread.', 'Eu quero te dar pão.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to give them water.', 'Eu quero dar água para eles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He wants to give me a car.', 'Ele quer me dar um carro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to give you a book.', 'Eu quero te dar um livro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to sell these books.', 'Eu quero vender estes livros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to sell these cars.', 'Eu quero vender estes carros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to sell these cups.', 'Eu quero vender estas xícaras.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to sell these houses.', 'Eu quero vender estas casas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see those birds?', 'Você vê aqueles pássaros?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see those dogs?', 'Você vê aqueles cachorros?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see those bikes?', 'Você vê aquelas bicicletas?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see those cars?', 'Você vê aqueles carros?', now(), 1);

INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I buy meat here.', 'Eu compro carne aqui.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I sell books here.', 'Eu vendo livros aqui.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I play soccer here.', 'Eu jogo futebol aqui.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I read books here.', 'Eu leio livros aqui.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('My sister works there.', 'Minha irmã trabalha lá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('My wife studies there.', 'Minha esposa estuda lá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('My son helps there.', 'Meu filho ajuda lá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('My parents eat there.', 'Meus pais comem lá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a letter from you.', 'Eu tenho uma carta sua.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a letter from my friend.', 'Eu tenho uma carta do meu amigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a letter from your sister.', 'Eu tenho uma carta da sua irmã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have a letter from the boss.', 'Eu tenho uma carta do chefe.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I see an animal.', 'Eu vejo um animal.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I see an Indian.', 'Eu vejo um indiano.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I see an apple.', 'Eu vejo uma maçã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I see an ace.', 'Eu vejo um ás.', now(), 1);

INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('why do you work? because i need to', 'por que você trabalha? porque eu preciso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('why do you study? because i have to.', 'por que você estuda? porque eu tenho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('why do you read? because i like to.', 'por que você lê? porque eu gosto.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('why do you help? because i want to.', 'por que você ajuda? porque eu quero.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('they work at the third house.', 'eles trabalham na terceira casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('they play at the third house.', 'eles brincam na terceira casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('they study at the third house.', 'eles estudam na terceira casa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want the second book.', 'eu quero o segundo livro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want the second cat.', 'eu quero o segundo gato.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want the second waitress.', 'eu quero a segunda garçonete.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('we want to work this morning.', 'nós queremos trabalhar esta manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('we want to play this morning.', 'nós queremos brincar esta manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('we want to study this morning.', 'nós queremos estudar esta manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('we want to read this morning.', 'nós queremos ler esta manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you have to go this afternoon.', 'você tem que ir esta tarde.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you have to help this afternoon.', 'você tem que ajudar esta tarde.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you have to write this afternoon.', 'você tem que escrever esta tarde.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you have to sell this afternoon.', 'você tem que vender esta tarde.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he works tonight.', 'ele trabalha esta noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he studies tonight.', 'ele estuda esta noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he speaks tonight.', 'ele fala esta noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he has dinner tonight.', 'ele janta esta noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you know how to read?', 'você sabe ler?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you know how to write?', 'você sabe escrever?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you know how to work?', 'você sabe trabalhar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you know how to buy?', 'você sabe comprar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i like to speak about my family.', 'eu gosto de falar sobre minha família.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i like to speak about the children.', 'eu gosto de falar sobre as crianças.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i like to speak about my work.', 'eu gosto de falar sobre meu trabalho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i like to speak about money.', 'eu gosto de falar sobre dinheiro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have about three birds.', 'eu tenho por volta de três pássaros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i know about seven numbers.', 'eu sei por volta de sete números.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i read about two books.', 'eu li por volta de dois livros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i write about five letters.', 'eu escrevo por volta de cinco cartas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('what do you think about the boss?', 'o que você pensa sobre o chefe?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('what do you think about this?', 'o que você acha disso?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('what do you think about your work?', 'o que você pensa sobre seu trabalho?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('what do you think about him?', 'o que você pensa sobre ele?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want to understand my friend, but I only speak English.', 'Eu quero entender meu amigo, mas eu só falo inglês.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I have money today, but I don’t want to go. See you later.', 'Eu tenho dinheiro hoje, mas eu não quero ir. Até logo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Why do you read in the morning? I don’t have time in the evening.', 'Por que você lê de manhã? Eu não tenho tempo à noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('When do you eat? I have lunch in the afternoon.', 'Quando você come? Eu almoço à tarde.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like to speak English with my family. We don’t speak Portuguese.', 'Eu gosto de falar inglês com minha família. Nós não falamos português.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('How many books do you have about animals? I have four books.', 'Quantos livros você tem sobre animais? Eu tenho quatro livros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I don’t eat at my home. I like to have dinner at the restaurant.', 'Eu não como em casa. Eu gosto de jantar no restaurante.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Where do you like to study? I only study at the school.', 'Onde você gosta de estudar? Eu só estudo na escola.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You don’t like to work at this store. Why do you work here?', 'Você não gosta de trabalhar nesta loja. Por que você trabalha aqui?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We don’t have time to go to the store with you today.', 'Nós não temos tempo para ir à loja com você hoje.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you want to buy a newspaper with this money? I don’t read.', 'Você quer comprar um jornal com esse dinheiro? Eu não leio.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('They want to write a letter this afternoon. Do you want to help?', 'Eles querem escrever uma carta esta tarde. Você quer ajudar?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I buy two books every week. Do you sell books or magazines?', 'Eu compro dois livros toda semana. Você vende livros ou revistas?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do your friends go to the school with you? I go by myself.', 'Seus amigos vão para a escola com você? Eu vou sozinho.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Why do your children go to the movies only on the weekend?', 'Por que seus filhos vão ao cinema apenas no fim de semana?', now(), 1);


INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i see your ties.', 'eu vejo suas gravatas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i your thighs.', 'eu suas coxas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he is a tinker.', 'ele é um ferramenteiro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he is a thinker.', 'ele é um pensador.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have a fate.', 'eu tenho um destino.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have a faith.', 'eu tenho uma fé.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('go to the fort wall.', 'vá para o muro do forte.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('go to the fourth wall.', 'vá para o quarto muro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('it’s a beautiful reef.', 'é um belo recife.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('it‘s a beautiful wreath.', 'é uma bela coroa.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have free tickets.', 'eu tenho ingressos grátis.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have three tickets.', 'eu tenho três ingressos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('come with me.', 'venha comigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('come whiff me.', 'venha sentir o cheiro comigo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('are you deaf?', 'você é surdo?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('are you death?', 'você é a morte?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you know me?', 'você me conhece?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('please, speak for us.', 'por favor, fale por nós.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i don''t see you.', 'eu não vejo você.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i speak to you all today.', 'eu falo com todos vocês hoje.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('she helps him.', 'ela ajuda ele.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have to go with them.', 'eu tenho que ir com eles.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('he needs her.', 'ele precisa dela.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i like it.', 'eu gosto disso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('give me the book!', 'me dê o livro!', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('you don’t want to give your time.', 'você não quer dar o seu tempo.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to give you this.', 'eu quero te dar isso.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('give me that!', 'me dê aquilo!', now(), 1);

INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like this book.', 'Eu gosto desse livro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like these books.', 'Eu gosto desses livros.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see this bird?', 'Você vê esse pássaro?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Do you see these birds?', 'Você vê esses pássaros?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want this magazine.', 'Eu quero essa revista.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Give me that letter.', 'Me dê aquela carta.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Give me those letters.', 'Me dê aquelas cartas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like that cat.', 'Eu gosto desse gato.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I want these magazines.', 'Eu quero essas revistas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I like those cats.', 'Eu gosto daqueles gatos.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i know how to read.', 'eu sei ler.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you know how to speak english?', 'você sabe falar inglês?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('we want to know how to go there.', 'nós queremos saber como ir lá.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have to work in the morning .', 'eu tenho que trabalhar de manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i have to work this morning.', 'eu tenho que trabalhar esta manhã.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you study in the afternoon?', 'você estuda à tarde?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('do you study this afternoon?', 'você estuda esta tarde?', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i go there in the evening.', 'eu vou lá à noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i go there tonight.', 'eu vou lá hoje à noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i go downtown everyday.', 'eu vou ao centro todos os dias.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i want to go home now.', 'eu quero ir para casa agora.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i work downtown.', 'eu trabalho no centro.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('i need to go north.', 'eu preciso ir para o norte.', now(), 1);


INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('already', 'já', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('usually', 'normalmente', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I work until two o''clock.', 'Eu trabalho até às duas horas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('You need to come home by nine o’clock.', 'Você precisa voltar para casa até às nove horas.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I can read books in English.', 'Eu consigo ler livros em inglês.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('He can go with us.', 'Ele pode ir conosco.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('We can’t open the store tonight.', 'Nós não podemos abrir a loja esta noite.', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('I can’t sleep!', 'Eu não consigo dormir!', now(), 1);
INSERT INTO frames(en, pt, next_test, num_right_answer) VALUES('Can I go with you?', 'Eu posso ir com você?', now(), 1);






update frames set num_right_answer = 10;


select * from frames f where next_test <= now() order by next_test;

